fullname: freqtrade-short

config:
  max_open_trades: 10
  trading_mode: "futures"
  margin_mode: "isolated"
  stake_currency: USDT
  stake_amount: 15
  amend_last_stake_amount: true
  tradable_balance_ratio: 0.995
  fiat_display_currency: "USD"
  timeframe: 1h
  dry_run: false
  dry_run_wallet: 3000
  cancel_open_orders_on_exit: false
  position_adjustment_enable: true
  max_entry_position_adjustment: 10
  trailing_stop: false
  liquidation_buffer: 0.005
  unfilledtimeout:
    entry: 5
    exit: 5
    exit_timeout_count: 0
    unit: minutes
  entry_pricing:
    price_side: other
    use_order_book: true
    order_book_top: 1
    price_last_balance: 0
    check_depth_of_market:
      enabled: false
      bids_to_ask_delta: 1
  exit_pricing:
    price_side: other
    use_order_book: true
    order_book_top: 1
  use_exit_signal: true
  exit_profit_only: false
  ignore_roi_if_entry_signal: false
  exchange:
    name: binance
    key: ''
    secret: ''
    ccxt_config:
      enableRateLimit: false
      rateLimit: 1000
    ccxt_async_config:
      enableRateLimit: false
      rateLimit: 1000
    pair_whitelist: ["BTC/USDT:USDT"]
    pair_blacklist: []

  pairlists:
  - method: StaticPairList
  #- method: "VolumePairList"
  #  number_assets: 150
  #  sort_key: "quoteVolume"
  #  min_value: 0
  #  refresh_period: 1800
  #- method: "AgeFilter"
  #  min_days_listed: 45

  edge:
    enabled: false
    process_throttle_secs: 3600
    calculate_since_number_of_days: 7
    allowed_risk: 0.01
    stoploss_range_min: -0.01
    stoploss_range_max: -0.1
    stoploss_range_step: -0.01
    minimum_winrate: 0.6
    minimum_expectancy: 0.2
    min_trade_number: 10
    max_trade_duration_minute: 1440
    remove_pumps: false
  telegram:
    enabled: false
    token: ''
    chat_id: ''
  api_server:
    enabled: true
    listen_ip_address: 0.0.0.0
    listen_port: 8080
    username: admin
    password: 'password'
    jwt_secret_key: "yadeZee6being3eBed8Gohr0aexample"
    CORS_origins:
    - "https://front.domain.com"    
    - "https://subtrader01.domain.com" 
  bot_name: freqtrade
  initial_state: running
  force_entry_enable: false
  internals:
    process_throttle_secs: 5

image:
  base: freqtradeorg/freqtrade
  tag: "2023.12"

backtesting:
  enabled: true
  download_data: true
  days: "365"
  timeframes: 1h
  strategy_list: Scalp
  fee: 0.002
  pvc_size: 1Gi

bot:
  enabled: true
  strategy_name: Scalp
  pvc_size: 1Gi

ingress:
  enabled: true
  host: front.domain.com

create_config_configmap: true
create_strategies_configmap: true

strategies: {}
