{{- if .Values.create_config_configmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: freqtrade-config-{{ .Values.fullname }}
data:
  config.json: |
{{ toPrettyJson .Values.config | indent 4 }}
{{- end }}
