{{- if (and .Values.bot.enabled .Values.config.api_server.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullname }}
  labels:
    app: {{ .Values.fullname }}
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: api
  selector:
    app: {{ .Values.fullname }}
{{- end }}
